- name: Inject WildKSU Driver
      run: |
        cd $GITHUB_WORKSPACE/kernel_vili
        rm -rf kernel/ksu
        git clone https://github.com/WildKernels/Wild_KSU.git kernel/ksu --depth=1

    - name: Apply SuSFS 2.2.0 Patches
      run: |
        cd $GITHUB_WORKSPACE/kernel_vili
        rm -rf susfs_src
        git clone https://github.com/simonpunk/susfs4ksu.git -b kernel-5.4 susfs_src --depth=1
        cp -r susfs_src/kernel_patches/fs/* fs/
        cp -r susfs_src/kernel_patches/include/linux/* include/linux/
        patch -p1 < susfs_src/kernel_patches/5.4/0001-susfs-v2.0.x-for-kernel-5.4.patch || true
